export const FETCH_SAMPLE_KIT_REQUEST = 'FETCH_SAMPLE_KIT_REQUEST'
export const FETCH_SAMPLE_KIT_SUCCESS = 'FETCH_SAMPLE_KIT_SUCCESS'
export const FETCH_SAMPLE_KIT_FAILURE = 'FETCH_SAMPLE_KIT_FAILURE'

export const FETCH_SAMPLE_REQUEST = 'FETCH_SAMPLE_REQUEST'
export const FETCH_SAMPLE_SUCCESS = 'FETCH_SAMPLE_SUCCESS'
export const FETCH_SAMPLE_FAILURE = 'FETCH_SAMPLE_FAILURE'

export const PLAY_SAMPLE_START = 'PLAY_SAMPLE_START'
export const PLAY_SAMPLE_STOP = 'PLAY_SAMPLE_STOP'
